version: 1.0.0
date: 2022-05-23
repos:
  java-sdk:
    location: https://github.com/ClickSend/clicksend-java
    icon: https://github.com/ClickSend/clicksend-java/icon.png # This doesn't exist
    title: The official Java library for ClickSend v3 API
    description: >
      This is the official  [ClickSend](https://clicksend.com/)  SDK. Documentation can be found  [here](https://developers.clicksend.com/docs/rest/v3/?java#introduction).

      Use this library to seamlessly incorporate the power of the ClickSend API directly into your Java application. 
    author: ClickSend
    author-link: https://www.clicksend.com
    operating-system: all
    human-language: English
    computer-languages:
      - java
  php-sdk:
    repo: https://github.com/ClickSend/clicksend-php
    icon: https://github.com/ClickSend/clicksend-php/icon.png
    title: The official PHP library for ClickSend v3 API
    description: >
      This is the official  [ClickSend](https://clicksend.com/)  SDK. Documentation can be found [here](https://developers.clicksend.com/docs/rest/v3/?php#introduction).
      
      Use this library to seamlessly incorporate the power of the ClickSend API directly into your PHP application.
    author: ClickSend
    author-link: https://www.clicksend.com
    operating-system: all
    human-language: English
    computer-languages:
      - php
